export const ACTIONS = Object.freeze({
  TEST_DISPATCH: 'TEST_DISPATCH',
  /* Users */
  REQUEST_USERS: 'REQUEST_USERS',
  RECEIVE_USERS: 'RECEIVE_USERS',
  CLEAR_USERS: 'CLEAR_USERS',
  /* Messages */
  REQUEST_MESSAGES: 'REQUEST_MESSAGES',
  RECEIVE_MESSAGES: 'RECEIVE_MESSAGES',
  CLEAR_MESSAGES: 'CLEAR_MESSAGES'
})
